apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secusphere.fullname" . }}
  labels:
    {{- include "secusphere.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "secusphere.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "secusphere.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "secusphere.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: VM_RUNTIME
              value: "prod"
            - name: PROD_DB_URI_REF
              value: "{{ .Values.azKeyVaultDbUriRefName }}"
            - name: SMTP_PW_REF
              value: "{{ .Values.azKeyVaultSmtpPasswordRefName }}"
            - name: AZURE_KEYVAULT_NAME
              value: "{{ .Values.azKeyVaultName }}"
            - name: APP_EXT_URL
              value: "https://{{ .Values.appName }}.{{ .Values.appDomain }}"
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: az-creds
                  key: clientid
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: az-creds
                  key: secret
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: az-creds
                  key: tenantid
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
