{{- if .Values.ingress.enabled -}}
{{- $fullName := .Values.appName -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "secusphere.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    meta.helm.sh/release-name: "{{ .Values.appName }}"
    meta.helm.sh/release-namespace: "{{ .Values.appName }}"
spec:
  tls:
    - hosts:
        - host: "{{ .Values.appName }}.{{ .Values.appDomain }}"
          paths:
            - path: /
              serviceName: "{{ .Values.appName }}"
              servicePort: 80
          servicePort: 80
      secretName: {{ .Values.tlsSecretName }}
  defaultBackend:
    service:
      name: {{ $fullName }}
      port:
        number: 80
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: 'secusphere'
                port:
                  number: {{ .servicePort }}
    {{- end }}
  {{- end }}