{{- if .Values.ingress.enabled -}}
{{- $fullName := .Values.appName -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "secusphere.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
    meta.helm.sh/release-name: "{{ .Values.appName }}"
    meta.helm.sh/release-namespace: "{{ .Values.appName }}"
spec:
  tls:
    - secretName: {{ .Values.tlsSecretName }}
      hosts:
        - "{{ .Values.appName }}.{{ .Values.appDomain }}"
  defaultBackend:
    service:
      name: {{ $fullName }}
      port:
        number: 80
  rules:
    - host: "{{ .Values.appName }}.{{ .Values.appDomain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.appName }}"
                port:
                  number: {{ $svcPort }}
  {{- end }}