global:
  appName: 'SECUSPHERE--SecuSphere'
  defaultBranches:
    - release
    - hotfix
    - security
stages:
  prepJob:
    enabled: true
    branches:
      - release
  unitTesting:
    enabled: false
    branches: []
  secretScanning:
    enabled: false
    branches:
      - release
  sca:
    enabled: false
    branches:
      - release
    codeLanguages:
      - Python
      - Javascript
  sast:
    enabled: false
    branches:
      - release
    codeLanguages:
      - Python
  iac:
    enabled: false
    branches:
      - release
  buildDocker:
    enabled: false
    branches:
      - release
  containerScan:
    enabled: false
    branches:
      - release
    containerName: secusphere
    containerTag: latest
  releaseToTest:
    enabled: false
    branches:
      - release
    serviceName: secusphere
    containerTag: latest
  testRelease:
    enabled: false
    branches:
      - release
    targetUrl: 'http://192.168.0.68:5010'
    dastTestType: full
    apiTargetUrl: 'http://192.168.0.68:5010/api/openapi.yaml'
  securityQualityGate:
    enabled: false
    branches:
      - release
  deploy:
    enabled: true
    branches:
      - release
    tlsCredId: 'su-tls-wildcard'
    secretsCredentials:
      azClientId: 'AZ-TF-client_id'
      azClientSecret: 'AZ-TF-client_secret'
      azTenantId: 'AZ-TF-tenant_id'
    secretsSetStrings:
      azure.credsEnabled: true
      azure.azClientId: 'azClientId'
      azure.azClientSecret: 'azClientSecret'
      azure.azTenantId: 'azTenantId'
    serviceCredentials: {}
    serviceSetStrings:
      app.extUrl: "192.168.0.150"
      app.db.prodDbUriRef: "PROD-DB-URI"
      app.smtp.host: "smtp.sendgrid.net:587"
      app.smtp.user: apikey
      app.smtp.adminEmail: "admin@securityuniversal.com"
      app.smtp.passwordRef: "SENDGRID-SMTP-PW"
      app.az.keyVaultName: "BkDevSecOpsKeyVault"
  post:
    enabled: false
    branches:
      - release
    recipientEmails: 'brian@jbfinegoods.com'
    recipientTeamsChannels: 'SecAutomation-Testing-Teams-Webhook'
