global:
  appName: 'SECUSPHERE--SecuSphere'
  defaultBranches:
    - release
    - hotfix
stages:
  prepJob:
    enabled: true
    branches:
      - release
  unitTesting:
    enabled: true
    branches: []
  secretScanning:
    enabled: true
    branches:
      - release
  sca:
    enabled: true
    branches:
      - release
    codeLanguages:
      - Python
      - Javascript
  sast:
    enabled: true
    branches:
      - release
    codeLanguages:
      - Python
  iac:
    enabled: true
    branches:
      - release
  buildDocker:
    enabled: true
    branches:
      - release
  containerScan:
    enabled: true
    branches:
      - release
    containerName: secusphere
    containerTag: latest
  releaseToTest:
    enabled: true
    branches:
      - release
    serviceName: secusphere
    containerTag: latest
  testRelease:
    enabled: true
    branches:
      - release
    targetUrl: 'http://192.168.0.68:5010'
    dastTestType: full
    apiTargetUrl: 'http://192.168.0.68:5010/api/openapi.yaml'
  securityQualityGate:
    enabled: true
    branches:
      - release
  deploy:
    enabled: true
    branches:
      - release
    tlsCredId: 'su-tls-wildcard'
    secretsCredentials:
      azClientId: 'AZ-TF-client_id'
      azClientSecret: 'AZ-TF-client_secret'
      azTenantId: 'AZ-TF-tenant_id'
    secretsSetStrings:
      azure.credsEnabled: true
      azure.azClientId: 'azClientId'
      azure.azClientSecret: 'azClientSecret'
      azure.azTenantId: 'azTenantId'
    serviceCredentials: {}
  post:
    enabled: true
    branches:
      - release
    recipientEmails: 'brian@jbfinegoods.com'
    recipientTeamsChannels: 'SecAutomation-Testing-Teams-Webhook'