{{- if .Values.azure.credsEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: az-creds
type: Opaque
data:
  clientid: {{ .Values.azure.azClientId | b64enc }}
  secret: {{ .Values.azure.azClientSecret | b64enc }}
  tenantid: {{ .Values.azure.azTenantId | b64enc }}
{{- end }}
