apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.name }}
  namespace: {{ .Values.appName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt }}
  tls.key: {{ .Values.tls.key }}
